AWSTemplateFormatVersion: 2010-09-09
Description: CFT Templates based on mapping values
  
Parameters:
  EnvironmentName:
    Type: String
    Description: Choosing ENV to deploy resource
    Default: local
    AllowedValues:
      - local
      - dev
      - stg
      - prod
  VPCID:
    Type: String
    Description: Enter The Existing VPC ID

  SubnetId:
    Type: String
    Description: Subnet of the VPC need to be used

  SecurityGroupId:
    Type: String
    Description: Enter the SecurityGroup ID

Mappings:
  RegionMap:
    ap-south-1:
      AMI: ami-00bb6a80f01f03502
    ap-northeast-1:
      AMI: ami-0c50b6f7dc3701ddd
  
  EnvironmentMap:
    dev:
      InstanceType: t2.small
    stg:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.medium

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: !FindInMap [EnvironmentMap , !Ref EnvironmentName , InstanceType]
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-instance
  
Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance

  InstancePublicIp:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
