AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple template to create EC2 instance using existing VPC resources'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-00bb6a80f01f03502  # Replace with a valid AMI ID
      # SecurityGroupIds: sg-0c928c7472050571a
      # SubnetId: subnet-09211d94bace0a331  # Ensure this Subnet ID exists in the specified VPC
      KeyName: test1